spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}/${DATABASE_NAME:balance}?currentSchema=public
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:docker}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          time_zone: UTC
          batch_size: 5
        order_updates: true
        order_inserts: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml

  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
server:
  port: 8081
logging:
  level:
    org: INFO
management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
